PLAYLIST_LIMIT = 10

DOWNLOAD_OPTIONS = ['Песня']

DOWNLOAD_START_STATE = 0
DOWNLOAD_OPTION_STATE = 1
RETRIEVE_METADATA_STATE = 2
DOWNLOAD_SONG_STATE = 3

OPTION_TO_STATE = {
  DOWNLOAD_OPTIONS[0]: RETRIEVE_METADATA_STATE
}